// <auto-generated />
using System;
using Backend.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RCSBackend.Migrations
{
    [DbContext(typeof(GrcsDbContext))]
    [Migration("20261001064614_AddRcsMapTables")]
    partial class AddRcsMapTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapLineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("direction");

                    b.Property<double>("Distance")
                        .HasColumnType("double")
                        .HasColumnName("distance");

                    b.Property<string>("FromPointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("from_point_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("line_code");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("double")
                        .HasColumnName("max_speed");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("ToPointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("to_point_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rcs_map_lines", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapPointRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_code");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_name");

                    b.Property<string>("PointType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<double>("X")
                        .HasColumnType("double")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double")
                        .HasColumnName("y");

                    b.Property<double>("Z")
                        .HasColumnType("double")
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.ToTable("rcs_map_points", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("coordinate_system");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<double>("OriginX")
                        .HasColumnType("double")
                        .HasColumnName("origin_x");

                    b.Property<double>("OriginY")
                        .HasColumnType("double")
                        .HasColumnName("origin_y");

                    b.Property<double>("OriginZ")
                        .HasColumnType("double")
                        .HasColumnName("origin_z");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scene_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("rcs_maps", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
