// <auto-generated />
using System;
using Backend.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace RCSBackend.Migrations
{
    [DbContext(typeof(GrcsDbContext))]
    [Migration("20261003074450_AddRcsAlgorithmSettings")]
    partial class AddRcsAlgorithmSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsAlgorithmSettingsRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvanceAfterPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("advance_after_points");

                    b.Property<int>("SegmentPointCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(4)
                        .HasColumnName("segment_point_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rcs_algorithm_settings", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapLineRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("direction");

                    b.Property<double>("Distance")
                        .HasColumnType("double")
                        .HasColumnName("distance");

                    b.Property<string>("FromPointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("from_point_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("line_code");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<double>("MaxSpeed")
                        .HasColumnType("double")
                        .HasColumnName("max_speed");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("ToPointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("to_point_code");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("rcs_map_lines", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapPointRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metadata_json");

                    b.Property<string>("PointCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_code");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_name");

                    b.Property<string>("PointType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("point_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<double>("X")
                        .HasColumnType("double")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double")
                        .HasColumnName("y");

                    b.Property<double>("Z")
                        .HasColumnType("double")
                        .HasColumnName("z");

                    b.HasKey("Id");

                    b.ToTable("rcs_map_points", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsMapRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CoordinateSystem")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("coordinate_system");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("map_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<double>("OriginX")
                        .HasColumnType("double")
                        .HasColumnName("origin_x");

                    b.Property<double>("OriginY")
                        .HasColumnType("double")
                        .HasColumnName("origin_y");

                    b.Property<double>("OriginZ")
                        .HasColumnType("double")
                        .HasColumnName("origin_z");

                    b.Property<string>("SceneName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("scene_name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("rcs_maps", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsTaskRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AreaCodesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("area_codes_json");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("container_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("finished_at");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("group_id");

                    b.Property<string>("MapCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("map_code");

                    b.Property<int>("MapVersion")
                        .HasColumnType("int")
                        .HasColumnName("map_version");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("message");

                    b.Property<string>("MsgTime")
                        .IsRequired()
                        .HasMaxLength(19)
                        .HasColumnType("varchar(19)")
                        .HasColumnName("msg_time");

                    b.Property<int>("PriorityCode")
                        .HasColumnType("int")
                        .HasColumnName("priority_code");

                    b.Property<string>("RequestedVehicleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("requested_vehicle_id");

                    b.Property<string>("RouteJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("route_json");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("source");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.Property<string>("StationActionsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("station_actions_json");

                    b.Property<string>("StationCodesJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("station_codes_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("status");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("task_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("warehouse");

                    b.HasKey("Id");

                    b.HasIndex("TaskId")
                        .IsUnique();

                    b.HasIndex("Status", "PriorityCode", "Id");

                    b.ToTable("rcs_tasks", (string)null);
                });

            modelBuilder.Entity("RCSBackend.Modules.Rcs.Infrastructure.Entities.RcsVehicleRow", b =>
                {
                    b.Property<string>("VehicleId")
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("vehicle_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("InitialPointCode")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("initial_point_code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasDefaultValue("AUTO")
                        .HasColumnName("operating_mode");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("protocol");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("VehicleId");

                    b.ToTable("rcs_vehicles", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
