// <auto-generated />
using GrcsBackend.Modules.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GrcsBackend.Migrations
{
    [DbContext(typeof(GrcsDbContext))]
    [Migration("20260902150720_AllBusinessTables")]
    partial class AllBusinessTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.AutoTemplateRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("steps_json");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("auto_templates", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.ExceptionRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("HappenedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("happened_at");

                    b.Property<string>("Phenomenon")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phenomenon");

                    b.Property<string>("Progress")
                        .HasColumnType("TEXT")
                        .HasColumnName("progress");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<int>("ReproduceCount")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reproduce_count");

                    b.Property<string>("ReproducedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reproduced_at");

                    b.Property<string>("ResponsibleDept")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("responsible_dept");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleCode")
                        .HasColumnType("TEXT")
                        .HasColumnName("vehicle_code");

                    b.HasKey("Id");

                    b.ToTable("exception_records", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.FeatureModuleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("module_id");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("api_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("params_json");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("feature_modules", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.KvRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("kv", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.MockRequestEventRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("event_key");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER")
                        .HasColumnName("attempts");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("body_json");

                    b.Property<string>("DecidedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("decided_at");

                    b.Property<long>("EventId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("event_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("MockRuleDescription")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mock_rule_desc");

                    b.Property<string>("MockRuleId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("mock_rule_id");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path_pattern");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("query_string");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.HasKey("Key");

                    b.ToTable("mock_request_events", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.MockRuleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("rule_id");

                    b.Property<bool>("AlsoRecord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("also_record");

                    b.Property<string>("ApprovalFalseValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_false_value");

                    b.Property<string>("ApprovalTrueValue")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_true_value");

                    b.Property<string>("ApprovalVariable")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("approval_variable");

                    b.Property<bool>("BoardSync")
                        .HasColumnType("INTEGER")
                        .HasColumnName("board_sync");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("enabled");

                    b.Property<string>("Matchers")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("matchers_json");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path_pattern");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER")
                        .HasColumnName("priority");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("INTEGER")
                        .HasColumnName("requires_approval");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("response_code");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("mock_rules", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.ModuleExecLogRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("detail");

                    b.Property<int>("HttpCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("http_code");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("module");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ok");

                    b.Property<string>("Point")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("point");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.ToTable("module_exec_logs", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.ProjectLogDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("LogDate")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("log_date");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("project");

                    b.Property<string>("Remark")
                        .HasColumnType("TEXT")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("project_logs", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.TaskRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CargoCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("cargo_code");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("container_code");

                    b.Property<bool>("Ok")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ok");

                    b.Property<string>("RouteCodes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("route_codes");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("station_code");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status_code");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_type");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("warehouse");

                    b.HasKey("Id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("idx_tr_stage");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_tr_task");

                    b.ToTable("task_records", (string)null);
                });

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.TaskTemplateRow", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<string>("ContainerPrefix")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("container_prefix");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("end_json");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("label");

                    b.Property<bool>("NeedsContainer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("needs_container");

                    b.Property<bool>("RandomContainer")
                        .HasColumnType("INTEGER")
                        .HasColumnName("random_container");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("start_json");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Value");

                    b.ToTable("task_templates", (string)null);
                });

            

            modelBuilder.Entity("GrcsBackend.Contracts.Entities.WorkflowStateRow", b =>
                {
                    b.Property<string>("Kind")
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.Property<string>("TaskId")
                        .HasColumnType("TEXT")
                        .HasColumnName("task_id");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("time");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Kind", "TaskId");

                    b.ToTable("workflow_state", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
