// <auto-generated />
using Backend.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace WCSBackend.Migrations;

[DbContext(typeof(GrcsDbContext))]
[Migration("20260915110000_AddModuleExecutionLogs")]
partial class AddModuleExecutionLogs
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
        => modelBuilder.HasAnnotation("ProductVersion", "10.0.9");
}
