// <auto-generated />
using Backend.Shared.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WCSBackend.Migrations
{
    [DbContext(typeof(GrcsDbContext))]
    partial class GrcsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Contracts.Entities.AutoTemplateRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("template_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("steps_json");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("auto_templates", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.ExceptionRecordDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_at");

                    b.Property<string>("HappenedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("happened_at");

                    b.Property<string>("Phenomenon")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("phenomenon");

                    b.Property<string>("Progress")
                        .HasColumnType("longtext")
                        .HasColumnName("progress");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("reason");

                    b.Property<int>("ReproduceCount")
                        .HasColumnType("int")
                        .HasColumnName("reproduce_count");

                    b.Property<string>("ReproducedAt")
                        .HasColumnType("longtext")
                        .HasColumnName("reproduced_at");

                    b.Property<string>("ResponsibleDept")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("responsible_dept");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.Property<string>("VehicleCode")
                        .HasColumnType("longtext")
                        .HasColumnName("vehicle_code");

                    b.HasKey("Id");

                    b.ToTable("exception_records", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.FeatureModuleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("module_id");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("api_url");

                    b.Property<string>("InventoryEffect")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventory_effect");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("params_json");

                    b.Property<string>("PreExecutionEffect")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pre_execution_effect");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("feature_modules", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.KvRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("kv", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.MockRequestEventRow", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("event_key");

                    b.Property<int>("Attempts")
                        .HasColumnType("int")
                        .HasColumnName("attempts");

                    b.Property<string>("BodyJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body_json");

                    b.Property<string>("DecidedAt")
                        .HasColumnType("longtext")
                        .HasColumnName("decided_at");

                    b.Property<long>("EventId")
                        .HasColumnType("bigint")
                        .HasColumnName("event_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<string>("MockRuleDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mock_rule_desc");

                    b.Property<string>("MockRuleId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("mock_rule_id");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("path_pattern");

                    b.Property<string>("QueryString")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("query_string");

                    b.Property<string>("RuleJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rule_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("time");

                    b.HasKey("Key");

                    b.ToTable("mock_request_events", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.MockRuleRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("rule_id");

                    b.Property<bool>("AlsoRecord")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("also_record");

                    b.Property<string>("ApprovalFalseValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("approval_false_value");

                    b.Property<string>("ApprovalTrueValue")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("approval_true_value");

                    b.Property<string>("ApprovalVariable")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("approval_variable");

                    b.Property<bool>("BoardSync")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("board_sync");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("Enabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("enabled");

                    b.Property<string>("Matchers")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("matchers_json");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("method");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("PathPattern")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("path_pattern");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("requires_approval");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("response_body");

                    b.Property<int>("ResponseCode")
                        .HasColumnType("int")
                        .HasColumnName("response_code");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("mock_rules", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.ModuleExecLogRow", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetailJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("detail_json");

                    b.Property<string>("ExecutionPhase")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("execution_phase");

                    b.Property<string>("FinishedAt")
                        .HasColumnType("longtext")
                        .HasColumnName("finished_at");

                    b.Property<int>("HttpStatus")
                        .HasColumnType("int")
                        .HasColumnName("http_status");

                    b.Property<string>("ModuleId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("module_id");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("module_name");

                    b.Property<string>("StartedAt")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("task_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("idx_module_exec_logs_started_at");

                    b.HasIndex("TaskId", "StartedAt")
                        .HasDatabaseName("idx_module_exec_logs_task_time");

                    b.ToTable("module_exec_logs", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.ProjectLogDto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("created_at");

                    b.Property<string>("LogDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("log_date");

                    b.Property<string>("Project")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("project");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("project_logs", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.TaskRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CargoCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cargo_code");

                    b.Property<string>("ContainerCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("container_code");

                    b.Property<string>("EndStationCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("end_station_code");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("stage");

                    b.Property<string>("StageStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("stage_status");

                    b.Property<string>("StartStationCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_station_code");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int")
                        .HasColumnName("status_code");

                    b.Property<string>("TaskId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("task_id");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task_type");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("time");

                    b.Property<string>("Warehouse")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("warehouse");

                    b.HasKey("Id");

                    b.HasIndex("Stage")
                        .HasDatabaseName("idx_tr_stage");

                    b.HasIndex("TaskId")
                        .HasDatabaseName("idx_tr_task");

                    b.ToTable("task_records", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.TaskTemplateRow", b =>
                {
                    b.Property<string>("Value")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("value");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("ContainerMode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("container_mode");

                    b.Property<string>("ContainerPrefix")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("container_prefix");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("End")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("end_json");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("label");

                    b.Property<bool>("NeedsContainer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("needs_container");

                    b.Property<bool>("RandomContainer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("random_container");

                    b.Property<string>("Start")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("start_json");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.HasKey("Value");

                    b.ToTable("task_templates", (string)null);
                });

            modelBuilder.Entity("Contracts.Entities.WcsSlotRow", b =>
                {
                    b.Property<string>("Mark")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("mark");

                    b.Property<string>("CargoCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("cargo_code");

                    b.Property<string>("CargoStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cargo_status");

                    b.Property<int>("Floor")
                        .HasColumnType("int")
                        .HasColumnName("floor");

                    b.Property<string>("PalletCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("pallet_code");

                    b.Property<string>("PalletStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("pallet_status");

                    b.Property<string>("ParentStationCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("parent_station_code");

                    b.Property<string>("SelectionStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("selection_status");

                    b.Property<string>("SiteType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("site_type");

                    b.Property<string>("TaskLockId")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("task_lock_id");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("updated_at");

                    b.Property<double>("X")
                        .HasColumnType("double")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double")
                        .HasColumnName("y");

                    b.HasKey("Mark");

                    b.HasIndex("CargoCode")
                        .HasDatabaseName("idx_slot_cargo");

                    b.HasIndex("PalletCode")
                        .HasDatabaseName("idx_slot_pallet");

                    b.ToTable("wcs_slots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
